# -*- coding: utf-8 -*-
"""diplom.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LbxxFE_ZrLRXNiWZ7Hdi3E42D3CKtE9A
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)
root_dir = "/content/gdrive/My Drive/"
base_dir = root_dir + 'diploma'
# %reload_ext autoreload
# %autoreload 2

!apt install -qq enchant
!pip install pyenchant
!pip install pymorphy2[fast]
!pip install -U pymorphy2-dicts-ru
!pip install gensim
!pip install --upgrade tensorflow
!pip install numpy scipy
!pip install scikit-learn
!pip install pillow
!pip install h5py
!pip install keras

#Установка необходимых библиотек
import json
import socket
import pandas as pd
import numpy as np
import enchant
import re
import regex
import pickle
import pymorphy2
morph = pymorphy2.MorphAnalyzer()
from gensim.models import Word2Vec
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, GlobalMaxPool1D, Conv1D, SpatialDropout1D
from keras.layers import Embedding, LSTM, GRU
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.sequence import pad_sequences
import keras.models

#сперва удалить крупные паттерны
pattern_clean_adress = regex.compile(r'адрес.+-\d{1,3}')
# удаление цифр и равно
pattern_clean_digits = regex.compile(r'\d+|=')
#удаление знаков препинания
pattern_clean_p = regex.compile(r'[^\P{P}]+')
# заменить ё на е
p_clean_1 = regex.compile(r'.данное заключение не является диагнозом и должно быть интерпретировано лечащим врачом на основании клинических и лабораторных данных')
p_clean_2 = regex.compile(r'данное заключение не является диагнозом, а наряду с результатами других исследований является одним из оснований для вынесения клинического диагноза в работе врача клинициста и должно быть правильно интерпретировано лечащим врачом в соответствии с клинической картиной')
p_clean_3 = regex.compile(r"клиническая информация|^рг|рг$| рг |rg$|^rg| rg |cor|^р | р$| р |cor|^r | r$| r |^ro | ro$| ro ")
p_clean_4 = regex.compile(r"ээд|доза| эд|эд |мзв|мвз|эффективная|эквивалентная")
p_clean_5 = regex.compile(r"не является диагнозом и интерпретируется лечащим врачом с учетом клинических и лабораторных данных|не является диагнозом")
p_s = regex.compile(r'\s+')
pattern_clean_list = [p_clean_1,p_clean_2,pattern_clean_adress,pattern_clean_digits,pattern_clean_p, p_clean_3, p_clean_4,  p_clean_5, p_s]
pattern_yo = regex.compile('ё')
def cleaner(row):
  new_row = row.lower()
  for pattern in pattern_clean_list:
    new_row = regex.sub(pattern, ' ', new_row)
    new_row = regex.sub('ё','е',new_row)
  return new_row.strip(' ')
add_pattern_clean = regex.compile(r'рентген\w* ')
def add_cleaner(row):
  new_row = regex.sub(add_pattern_clean,' ', row)
  new_row = regex.sub('\s+',' ', new_row)
  return new_row

# лемматизаторы
def lemmatizer_list(string):
  new_string = []
  for word in string.split(' '):
    p = morph.parse(word)[0]
    new_string.append(p.normal_form)
  return new_string
def lemmatizer_string(string):
  new_string = []
  for word in string.split(' '):
    p = morph.parse(word)[0]
    new_string.append(p.normal_form)
  return ' '.join(new_string)

#паттерны для нормы
pattern_norm_1 = re.compile(r'не обнаруж')
pattern_norm_2 = re.compile(r'не определя')
pattern_norm_3 = re.compile(r'не выявл')
pattern_norm_4 = re.compile(r'не найден')
pattern_norm_5 = re.compile(r'без.+патологи')
pattern_norm_6 = re.compile(r'без.+изменен')
pattern_norm_7 = re.compile(r'не отме')
pattern_norm_8 = re.compile(r'не получен')
pattern_norm_9 = re.compile(r'изменений.+нет')
pattern_norm_10 = re.compile(r'признаков.+нет')
pattern_norm_11 = re.compile(r'данных за.+нет')
pattern_norm_13 = re.compile(r'без патол')
pattern_norm_14 = re.compile(r'в пределах.+норм')
pattern_norm_15=re.compile(r'без.+данных.+за')
pattern_norm_16=re.compile(r'возрастн.+изменен')
pattern_norm_17=re.compile(r'без.{1,20}тен')
pattern_norm_18=re.compile(r'усилен.+легочн.+рисун')
pattern_norm_19=re.compile(r'не установлен')
pattern_norm_20=re.compile(r'бронхит')
pattern_norm_21=re.compile(r'пневмофиброз|пневмосклеро')
pattern_norm_25 = re.compile(r'без .* тене')
pattern_norm_26 = re.compile(r'остаточн|резидуальн|перенесенн')
pattern_norm_27 = re.compile(r'без .*признаков')
pattern_norm_list = [pattern_norm_1,pattern_norm_2,pattern_norm_3,
                     pattern_norm_4,pattern_norm_5,pattern_norm_6,pattern_norm_7,pattern_norm_8,
                    pattern_norm_9,pattern_norm_10,pattern_norm_11,pattern_norm_13,
                    pattern_norm_14,pattern_norm_15,pattern_norm_16,pattern_norm_17,pattern_norm_18,pattern_norm_19,
                    pattern_norm_20,pattern_norm_21,pattern_norm_25,pattern_norm_26,pattern_norm_27]

def labeller_norm(row, mode='model'):
  if mode=='model':
    score_norm = 0
    for pattern in pattern_norm_list:
        if re.findall(pattern, str(row)):
            score_norm+=1
    return score_norm
  else:
    score_norm_arr = []
    for pattern in pattern_norm_list:
        score_norm_arr.append(len(re.findall(pattern, str(row))))
    return score_norm_arr

#инфильтрация
pattern_inf_1 = regex.compile(r'(смазан|нечетк|сгущен|не четк|без четк|негомоген|очаговоподобн|снижен.+(пневматизац|прозрачност|воздушност)|понижен.+(пневматизац|прозрачност)).+(?= пневмони| плевропневмони)') 
pattern_inf_2 = regex.compile(r'участ.{1,29}инфильтр')
# pattern_inf_3 = regex.compile(r'пневмосклероз.{1,29}инфильтр')
# pattern_inf_4 =regex.compile(r'(?<!без .*)инфильтр(?!.+ не)')
pattern_inf_5 = regex.compile(r' матово')
pattern_inf_6 = regex.compile(r'SEP.*бронх.{1,7} инфильтр')
pattern_inf_7 = regex.compile(r'SEP.*перибронхиальн.+ инфильтр')
pattern_inf_8 = regex.compile(r'воспалительн.{1,4} инфильтр')
pattern_inf_list = [pattern_inf_1,pattern_inf_2,pattern_inf_5,pattern_inf_6,pattern_inf_7,pattern_inf_8]
def labeller_inf(row, mode='model'):
    score_inf = 0
    score_inf_arr=[]
    for pattern in pattern_inf_list:
        if regex.findall(pattern, str(row)):
            score_inf+=1
        score_inf_arr.append(len(regex.findall(pattern, str(row))))
    if regex.findall(r'(смазан|нечетк|сгущен|очаговоподобн|снижен.+(пневматизац|прозрачност|воздушност)|понижен.+(пневматизац|прозрачност|воздушност)).+(?=бронхит)',str(row)):
      score_inf-=1
    score_inf_arr.append(len(regex.findall(r'(смазан|нечетк|сгущен|очаговоподобн|снижен.+(пневматизац|прозрачност|воздушност)|понижен.+(пневматизац|прозрачност|воздушност)).+(?=бронхит)',str(row))))
    if not labeller_norm(regex.findall(r'SEP.+',row)) and regex.findall(r'SEP.+ пневмони',row):
      score_inf+=1
      score_inf_arr.append(1)
    else:
      score_inf_arr.append(0)
    if not labeller_norm(regex.findall(r'SEP.+',row)) and regex.findall(r'SEP.+инфильтр',row):
      score_inf+=1
      score_inf_arr.append(1)
    else:
      score_inf_arr.append(0)
    if not labeller_norm(regex.findall(r'SEP.+',row)) and regex.findall(pattern_inf_2,row):
      score_inf+=1
    if not labeller_norm(regex.findall(r'SEP.+',row)) and regex.findall(r'SEP.+фокус\w{0,3} \w{0,6}фиброз|SEP.+очаг\w{0,4} \w{0,6}фиброз|SEP.+очаг\w{0,4} \w{0,6}склероз',row):
      score_inf+=1
    score_inf_arr.append(len(regex.findall(r'SEP.+фокус\w{0,3} \w{0,6}фиброз|SEP.+очаг\w{0,4} \w{0,6}фиброз|SEP.+очаг\w{0,4} \w{0,6}склероз',row)))
    if not labeller_norm(regex.findall(r'SEP.+',row)) and regex.findall('SEP.+вирусн',row):
      score_inf+=1
    score_inf_arr.append(len(regex.findall('SEP.+вирусн',row)))
    if mode=='model':
      return score_inf
    else:
      return score_inf_arr

#вЫПОТ
pattern_hydro_1 = regex.compile(r'(SEP.+выпот|SEP.+гемоторакс|SEP.+гидроторакс|SEP.+жидкост|SEP.+эмпием|SEP.+гидропневмоторакс|SEP.+пневмогидроторакс)(?!.{0,2} не|.{0,2} нет)')
pattern_hydro_2 = regex.compile(r'(выпот|гемоторакс|гидроторакс|жидкост|эмпием|гидропневмоторакс|пневмогидроторакс)(?!.{0,2} не|.{0,2} нет).*SEP.+плеврит')
pattern_hydro_3 = regex.compile(r'(выпот|гемоторакс|гидроторакс|жидкост|эмпием|гидропневмоторакс|пневмогидроторакс)(?!.{0,2} не|.{0,2} нет).*SEP.+плевропневмони')
pattern_hydro_list = [pattern_hydro_1,pattern_hydro_2,pattern_hydro_3]
def labeller_hydro(row, mode='model'):
    score_hydro = 0
    score_hydro_arr = []
    for pattern in pattern_hydro_list:
        if regex.findall(pattern, str(row)):
            score_hydro+=1
        score_hydro_arr.append(len(regex.findall(pattern, str(row))))
    if mode=='model':
      return score_hydro
    else:
      return score_hydro_arr

# пневмоторакс
pattern_pneumo_1 = regex.compile(r'(пневмоторакс|гидропневмоторакс|пневмогидроторакс)(?!.{0,2} не)')
pattern_pneumo_list = [pattern_pneumo_1]
def labeller_pneumo(row, mode='model'):
    score_pneumo = 0
    score_pneumo_arr=[]
    for pattern in pattern_pneumo_list:
        if regex.findall(pattern, str(row)):
            score_pneumo+=1
        score_pneumo_arr.append(len(regex.findall(pattern, str(row))))
    if mode=='model':
      return score_pneumo
    else:
      return score_pneumo_arr

#emptiness
pattern_empty_1 = regex.compile(r'распад|абсцес|кольцевидн|кист\w{0,1}')
pattern_empty_2 = regex.compile(r'(?<!грудн\w+|плевральн\w+|брюш\w+) полост\w+ (?!груд\w+|плевры|брюш\w+)|полое|полый')
pattern_empty_list = [pattern_empty_1,pattern_empty_2]
def labeller_empty(row, mode='model'):
    score_empty = 0
    score_empty_arr=[]
    for pattern in pattern_empty_list:
        if regex.findall(pattern, str(row)):
            score_empty+=1
            print(regex.findall(pattern, str(row)))
        score_empty_arr.append(len(regex.findall(pattern, str(row))))
    if mode=='model':
      return score_empty
    else:
      return score_empty_arr
#диссеминация
# pattern_dissem_1 = regex.compile(r'множественны.{1,20}очаг')
pattern_dissem_2 = regex.compile(r'диссем')
pattern_dissem_list = [pattern_dissem_2]
def labeller_dissem(row, mode='model'):
    score_dissem = 0
    score_dissem_arr=[]
    for pattern in pattern_dissem_list:
        if regex.findall(pattern, str(row)):
            score_dissem+=1
        score_dissem_arr.append(len(regex.findall(pattern, str(row))))
    if mode=='model':
      return score_dissem
    else:
      return score_dissem_arr

def labeller_different_test(row,mode='model'):
  score_different_arr = []
  if mode=='model':
    score_different = 0
    if regex.findall(r'кардиомегал|ателекта|кальцинат|кальцинированная тень|кальцинированный очаг|петрификат', row):
      score_different +=1
      print(regex.findall(r'кардиомегал|ателекта|кальцинат|кальцинированная тень|кальцинированный очаг|петрификат', row))
    score_different_arr.append(len(regex.findall(r'кардиомегал|ателекта|кальцинат|кальцинированная тень|кальцинированный очаг|петрификат', row)))
    if regex.findall(r'(перелом)(?!\w*( \w+){0,2} ключиц|\w*( \w+){0,2} позвон)|(мозол)(?!\w*( \w+){0,2} ключиц)', row):
      score_different +=1
      
      print(regex.findall(r'(перелом)(?!\w*( \w+){0,2} ключиц|\w*( \w+){0,2} позвон)|(мозол)(?!\w*( \w+){0,2} ключиц)', row))
    score_different_arr.append(len(regex.findall(r'(перелом)(?!\w*( \w+){0,2} ключиц|\w*( \w+){0,2} позвон)|(мозол)(?!\w*( \w+){0,2} ключиц)', row)))
    if regex.findall(r'позвонк|позвонок', row):
      score_different-=1
      
      print('позвонк|позвонок')
    score_different_arr.append(len(regex.findall(r'позвонк|позвонок', row)))
    if regex.findall(r'обызвествл\w+( \w*){0,1} туб', row):
      score_different+=1
    
      print('обызвествл туб комплекс')
    score_different_arr.append(len((regex.findall(r'обызвествл\w+( \w*){0,1} туб', row))))

    return score_different
  else:
    return score_different_arr

# очаг
pattern_focus_1 = regex.compile(r'узел')
oma = regex.compile(r'гаматром[аы]|опухол')
pattern_focus_3 = regex.compile(r'^очаг |очаг$| очаг |^очага|очага$| очага |^очаги|очаги$| очаги')
pattern_focus_4 = regex.compile(r'(?<!диффузн\w+ )очаг\w* \w*фиброз')
pattern_focus_5 = regex.compile(r'участ\w+.{0,20} уплотнени\w+ \w четким|участ\w+.{0,20} уплотнени/w+ /w ровным|участ\w+.{1,20} уплотнени\w+.{0,2} размер')
pattern_focus_6 = regex.compile(r'(?<! без (\w+ ){0,3})(доп\w* образован|доп\w* тен|очагов\w+ тен|очагов\w+ образован|очаг\w* уплотнени|очаг\w* затемнени|объемно\w+ образовани)(?!\w+( \w+){0,6} не |\w+( \w+){0,3} нет )')
pattern_focus_7 = regex.compile(r'(кругл|шаровидн|овальн)\w+ тен|(кругл|шаровидн|овальн)\w+ образован|(кругл|шаровидн|овальн)\w+ форм|(кругл|шаровидн|овальн|овоидн)\w+ фокус')
pattern_focus_8 = regex.compile(r'(образован| тен| форм)\w+ кругл|(образован| тен| форм)\w+ шаровидн|(образован| тен| форм)\w+ овальн|(образован| тен| форм)\w+ округл')
pattern_focus_9 = regex.compile(r'(?<! без (\w+ ){0,3})(очаг\w* тен)(?!\w+( \w+){0,6} не |\w+( \w+){0,3} нет )')
pattern_focus_list=[pattern_focus_1,pattern_focus_3,pattern_focus_4,pattern_focus_5,pattern_focus_6,
                    pattern_focus_7,pattern_focus_8,oma, pattern_focus_9]
def labeller_focus_test(row, mode='model'):
  score_focus = 0
  score_focus_arr=[]
  for pattern in pattern_focus_list:
    if regex.findall(pattern, row):
      score_focus+=1
      print(regex.findall(pattern, row))
    score_focus_arr.append(len(regex.findall(pattern, row)))
  if labeller_inf(row) and regex.findall(r'очаговоподобн.+SEP',row):
    score_focus+=1
    print(regex.findall(r'очаговоподобн.+SEP',row))
  score_focus_arr.append(len(regex.findall(r'очаговоподобн.+SEP',row)))
  if labeller_inf(row) and regex.findall(r'SEP.+очагов.{0,3} пневмон',row):
    score_focus+=1
    print(regex.findall(r'SEP.+очагов.{0,3} пневмон',row))
  score_focus_arr.append(len(regex.findall(r'SEP.+очагов.{0,3} пневмон',row)))
  if not labeller_inf(row) and regex.findall(r'фокус',row):
    score_focus+=1
    print('фокус без пневмонии')
  score_focus_arr.append(len(regex.findall(r'фокус',row)))
  if regex.findall(r'SEP.* норм|SEP.* возраст', row):
    score_focus=0
    print('норм возраст')
  if regex.findall(r'кальцинат|петрификат', row):
    score_focus=0
    print('кальцинат петрификат')
  score_focus_arr.append(len(regex.findall(r'кальцинат|петрификат', row)))
  if regex.findall(r'липом|грыж|(?<!грудн\w+|плевральн\w+) полост\w+ (?!груд\w+|плевры)', row):
    score_focus=0
    print('липома, грыжа, полость')
  score_focus_arr.append(len(regex.findall(r'липом|грыж|(?<!грудн\w+|плевральн\w+) полост\w+ (?!груд\w+|плевры)', row)))
  if regex.findall(r'сосок|соск\w+', row):
    score_focus-=2
    print('сосок')
    score_focus_arr.append(1)
  else:
    score_focus_arr.append(0)
  if regex.findall(r'туб\w* очаг|очаг\w* туб', row):
    score_focus+=1
    print('туберкулез')
    score_focus_arr.append(1)
  else:
    score_focus_arr.append(0)
  if mode=='model':
    return score_focus
  else:
    return score_focus_arr

def labeller(row):
  norm=0
  hydro = 1 if labeller_hydro(row['description']+' SEP '+row['result'])>0 else 0
  pneumo = 1 if labeller_pneumo(row['result'])>0 else 0
  focus = 1 if labeller_focus_test(row['description']+' SEP '+row['result'])>0 else 0
  try:
    inf = 1 if labeller_inf(row['description']+' SEP '+row['result'])>0 else 0
  except:
    print(row['description'])
  dissem = 1 if labeller_dissem(row['result'])>0 else 0
  empty = 1 if labeller_empty(row['description']+' SEP '+row['result'])>0 else 0
  other = 1 if labeller_different_test(row['description']+' SEP '+row['result'])>0 else 0
  if all([hydro==0,pneumo==0,focus==0,inf==0,dissem==0,empty==0,other==0]):
    norm = 1
  row['hydro']=hydro
  row['pneumo']=pneumo
  row['focus']=focus
  row['inf']=inf
  row['dissem']=dissem
  row['empty']=empty
  row['norm']=norm
  row['other']=other
  if hydro>0:
    print(row['hydro'])
  return(row)

#после лемматизации появляются буквы "ё", убираем их
def yo(string):
  return string.replace('ё','е')

# корректор
pwl = enchant.request_pwl_dict(base_dir+'/vocab.txt')
pwl.remove('клети')
def corrector(string):
  res_list = []
  res=None
  suggestion = None
  for word in string.split(' '):
    try:
      suggestion = pwl.suggest(word)
      if suggestion:
        res_list.append(suggestion[0].strip())
      else:
        res_list.append(word)
    except:
      pass
  res = ' '.join(res_list)
  return res

def preprocess(row):
  row['description']=yo(lemmatizer_string(corrector(add_cleaner(cleaner(row['description'])))))
  row['result']=yo(lemmatizer_string(corrector(add_cleaner(cleaner(row['result'])))))
  return row

#загрузить эмбеддинги
from gensim.models import KeyedVectors
word2vec_model = KeyedVectors.load(base_dir+'/w2v')

#функция для перевода слов в индексы
def word2index(string):
  source_word_indices = []
  string_arr = string.split(' ')
  for i in range(len(string_arr)):
        word = string_arr[i]
        if word in word2vec_model.wv.vocab:
            word_index = word2vec_model.wv.vocab[word].index
            source_word_indices.append(word_index)
        else:
            # Do something. For example, leave it blank or replace with padding character's index.
            pass
  return np.array(source_word_indices)
#ограничить длину
def pad_seq(row):
  return pad_sequences(np.array([row]),maxlen=200)

#импорт моделей
model_focus = keras.models.load_model(base_dir+'/keras_focus_072')
model_inf = keras.models.load_model(base_dir+'/best_models/inf')
with open(base_dir+'/best_models/log_model_focus.pkl', 'rb') as f:
  log_model_focus = pickle.load(f)
# функции для предсказания моделями метки класса
def prediction_focus(row):
  concat = row['description']+"SEP"+row['result']
  vectors = word2index(concat)
  padded_array = pad_seq(vectors)
  keras_focus = float(model_focus.predict(padded_array)[0])
  score_focus = float(row['focus'])
  answer = log_model_focus.predict_proba(np.array([[keras_focus,score_focus]]))[0][1]
  row['focus']=answer
  return row
def prediction_inf(row):
  concat = row['description']+"SEP"+row['result']
  vectors = word2index(concat)
  padded_array = pad_seq(vectors)
  keras_inf = float(model_inf.predict(padded_array)[0])
  row['inf_answer']=keras_inf
  return row

def get_labels(row):
  preprocessed = preprocess(row)
  labels = labeller(preprocessed)
  labels = prediction_focus(labels)
  labels = prediction_inf(labels)
  return labels

def main():
  # row = {'description':'в огк обнаружена патологическая прозрачность и скорее всего выпот в плевральной полости', 'result':'гидроторокс',
  #      'pneumo':0,'focus':0,'inf':0,'dissem':0,'empty':0,'norm':0,'other':0}
  # return get_labels(row)
  sock = socket.socket()
  sock.bind(('', 9090))
  sock.listen(5)
  conn, addr = sock.accept()
  print('connected:', addr)
  row_ = conn.recv(5000)
  row = json.load(row_)
  res = get_labels(row)
  row_json = json.dumps(row)
  conn.send(row_json)

while True:
  main()

